# 应用名称
spring:
  application:
    name: maven-self-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uedu?characterEncoding=utf-8
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.edu.pojo
  mapper-locations: classpath:mappers/*Mapper.xml

