#swagger整合
swagger:
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.9.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: guihaole
    url: http://blog.didispace.com
    email: 2033443140@qq.com
  base-package: com.edu.controller
  base-path: /**
