server:
  port: 8081
spring:
  redis:
    host: 116.205.230.80
    port: 6375
    password: 1234
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1ms
        min-idle: 0
      shutdown-timeout: 100ms
